name: Matoonigokko16
version: '${version}'
main: com.petlin.matoonigokko16.Matoonigokko16
api-version: 1.16
authors: [ precious_mozuku ]
#depend: [ ProtocolLib ]

commands:
  settei:
    description: /
